services:
  - type: web
    name: spotify-now-playing
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REFRESH_TOKEN
        sync: false
